version: "3.9"

services:
  db:
    image: postgres:16-alpine
    container_name: dockerized-db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    ports:
      - "5432:5432"

  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: dockerized-app:local
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - APP_PORT=${APP_PORT:-5000}
    ports:
      - "5000:5000"

volumes:
  pgdata:
